### PR TITLE
Unit Tests for Alerts & Windows Page

### PR DESCRIPTION
**Pull request by egecansen**

### CODE REVIEW

**Comment by InnaDrapii** [comment]
Great job!

**Comment by Umutayb** [comment]
Add assertions and manually test negative cases to verify the assertions before pushing.

**Review by Umutayb — CHANGES_REQUESTED** [review]
Add assertions and manually test negative cases to verify the assertions before pushing.

**Comment by egecansen** [comment]
I used webInteractions.verifyCurrentUrl(); method for assertion

**Pull request merged**
